name: Update Movie and Session Databases

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMDB_USER_ID: ur162389474

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Run update script
        run: |
          pip install -r requirements.txt
          python medeia.py -u $IMDB_USER_ID --reload

      - name: Commit changes to /data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          COMMIT_MESSAGE="Update databases"
          [[ "${GITHUB_EVENT_NAME:-}" == "schedule" ]] && COMMIT_MESSAGE+=" ($(date +'%Y-%m-%d %H:00'))"

          git commit -m "$COMMIT_MESSAGE"
          git push

      - name: Upload storage directory artifact
        uses: actions/upload-artifact@v4
        with:
          name: storage
          path: storage/
